sudo: true
language: java
cache:
  directories:
    - $HOME/.m2
    - .cpcache
install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.492.sh
  - chmod +x linux-install-1.10.1.492.sh
  - sudo ./linux-install-1.10.1.492.sh
script:
  - clojure -A:test
  - curl -F 'json_file=@target/coverage/coveralls.json' https://coveralls.io/api/v1/jobs
branches:
  only:
  - master
